name: ai_recipe_generation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  async: ^2.11.0
  camera: ^0.10.5+9
  cloud_firestore: ^5.6.3
  device_info_plus: ^11.3.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_login: ^5.0.0
  flutter_markdown: ^0.7.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.0
  image_picker: ^1.0.7
  material_symbols_icons: ^4.2719.1
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sticky_headers: ^0.3.0+2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
