// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwURCJWwsrdTMEhYW_qeN5BQVU4qvw520',
    appId: '1:267593015422:web:e9621df5bcab40c99ab82f',
    messagingSenderId: '267593015422',
    projectId: 'technovation-2025',
    authDomain: 'technovation-2025.firebaseapp.com',
    storageBucket: 'technovation-2025.firebasestorage.app',
    measurementId: 'G-L6EKF5N1RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFYJ3z6JrNc7LO8ls3xXfU8mGOrxKDco',
    appId: '1:267593015422:android:358ab013fa5ca6f49ab82f',
    messagingSenderId: '267593015422',
    projectId: 'technovation-2025',
    storageBucket: 'technovation-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmq_fn1HkRYb5_YG9f837gxOk-7FKWK9E',
    appId: '1:267593015422:ios:3f6fe0aaea5f6cef9ab82f',
    messagingSenderId: '267593015422',
    projectId: 'technovation-2025',
    storageBucket: 'technovation-2025.firebasestorage.app',
    iosBundleId: 'com.example.technovationProject2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmq_fn1HkRYb5_YG9f837gxOk-7FKWK9E',
    appId: '1:267593015422:ios:3f6fe0aaea5f6cef9ab82f',
    messagingSenderId: '267593015422',
    projectId: 'technovation-2025',
    storageBucket: 'technovation-2025.firebasestorage.app',
    iosBundleId: 'com.example.technovationProject2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwURCJWwsrdTMEhYW_qeN5BQVU4qvw520',
    appId: '1:267593015422:web:9fa9dce2468c44c49ab82f',
    messagingSenderId: '267593015422',
    projectId: 'technovation-2025',
    authDomain: 'technovation-2025.firebaseapp.com',
    storageBucket: 'technovation-2025.firebasestorage.app',
    measurementId: 'G-DXBG72D58T',
  );
}
